version: "3.2"
services: 
  db:
    image: postgres
    restart: always
    network_mode: host
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: user
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  webapp:
    image: 460700981334.dkr.ecr.eu-central-1.amazonaws.com/dft-ui:latest
    ports:
      - "3000:80"
      - "3000:443"

  rest-api:
    depends_on:      
      - db
    image: 460700981334.dkr.ecr.eu-central-1.amazonaws.com/dft-api:latest
    network_mode: host
    ports:
      - "8080:8080"
